replicaCount: 3

image:
  repository: docker.io/fifia/springboot-app
  tag: latest

service:
  type: LoadBalancer

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
